# Generated by Django 4.0.5 on 2022-06-06 19:40

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(default='images/No_image.png', max_length=255, upload_to=images.models.upload_to, verbose_name='File Name')),
                ('alt_text', models.CharField(blank=True, max_length=50, verbose_name='Alt Text')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('mimeType', models.CharField(max_length=255, verbose_name='Mime Type')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
