# Generated by Django 4.0.5 on 2022-07-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='mimeType',
            new_name='mime_type',
        ),
    ]
