# Generated by Django 4.0.5 on 2022-07-14 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_mimetype_image_mime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='mime_type',
        ),
    ]
