# Generated by Django 4.0.5 on 2022-07-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mime_type',
            field=models.CharField(default='png', max_length=25, verbose_name='Mime Type'),
            preserve_default=False,
        ),
    ]
