# Generated by Django 4.0.5 on 2022-11-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_name',
            field=models.ImageField(default='images/No_image.png', max_length=255, upload_to='images', verbose_name='File Name'),
        ),
    ]
