# Generated by Django 4.0.5 on 2022-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_name',
            field=models.ImageField(default='No_image.png', max_length=255, upload_to='', verbose_name='File Name'),
        ),
    ]
