# Generated by Django 4.0.5 on 2022-11-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, default={'C:\\Users\\cmyer\\OneDrive\\CMC Services\\Desktop\\Projects\\sprint_to_success\\rabbit_hole_backend\\rabbit_hole_prj'}, verbose_name='URL'),
        ),
    ]
