# Generated by Django 4.0.5 on 2022-11-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='orig_dir',
            field=models.CharField(blank=True, default='C:\\Users\\cmyer\\OneDrive\\CMC Services\\Desktop\\Projects\\sprint_to_success\\rabbit_hole_backend\\rabbit_hole_prj', max_length=200, verbose_name='Directory'),
        ),
    ]
