# Generated by Django 4.0.5 on 2022-11-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_remove_image_orig_dir_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
