# Generated by Django 4.0.5 on 2022-11-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='rabbit_hole',
        ),
    ]
