# Generated by Django 4.0.5 on 2022-11-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_remove_solution_rabbit_hole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='description'),
        ),
    ]
