# Generated by Django 4.0.5 on 2022-06-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rabbit_Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=10, verbose_name='Log Type')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('rating', models.IntegerField(default=0, verbose_name='rating')),
                ('solution', models.BooleanField(default=False, verbose_name='solution')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.project')),
            ],
            options={
                'verbose_name': 'Rabit Hole',
                'verbose_name_plural': 'Rabbit Holes',
                'ordering': ('-created_at',),
            },
        ),
    ]
