# Generated by Django 4.0.5 on 2022-06-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('rabbit_holes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit_hole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.project'),
        ),
    ]
