# Generated by Django 4.0.5 on 2022-06-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit_holes', '0002_alter_rabbit_hole_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit_hole',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
    ]
