# Generated by Django 4.0.5 on 2022-11-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_alter_solution_description'),
        ('rabbit_holes', '0003_rabbit_hole_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit_hole',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.solution'),
        ),
    ]
