# Generated by Django 4.0.5 on 2022-06-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-name',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
