# Generated by Django 4.0.5 on 2022-11-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_file_name'),
        ('projects', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image'),
        ),
    ]
