# Generated by Django 4.0.5 on 2022-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text_color',
            field=models.CharField(default='#000000', max_length=50, verbose_name='text color'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme_color',
            field=models.CharField(default='#00a2ed', max_length=50, verbose_name='theme color'),
        ),
    ]
