# Generated by Django 4.0.5 on 2022-06-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_text_color_project_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, verbose_name='abbreviation'),
        ),
    ]
